// reactjs-files/template/gradient-pink/src/components/login/index.jsx
import React, { Component } from "react";
import { Link } from "react-router-dom";
import IMG01 from "../../assets/images/logo.png";

class Login extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div className="main-wrapper">
        <div className="account-content">
          <div className="container">
            <div className="account-logo">
              <Link to="/">
                <img src={IMG01} alt="Dreamguy's Technologies" />
              </Link>
            </div>

            <div className="account-box">
              <div className="account-wrapper">
                <h3 className="account-title">Login</h3>
                <p className="account-subtitle">Access to our dashboard</p>

                <form action="index.html">
                  <div className="form-group">
                    <label>Email Address</label>
                    <input className="form-control" type="text" />
                  </div>
                  <div className="form-group">
                    <div className="row">
                      <div className="col">
                        <label>Password</label>
                      </div>
                      <div className="col-auto">
                        <Link className="text-muted" to="/forgot-password">
                          Forgot password?
                        </Link>
                      </div>
                    </div>
                    <input className="form-control" type="password" />
                  </div>
                  <div className="form-group text-center">
                    <button className="btn btn-primary account-btn" type="submit">
                      Login
                    </button>
                  </div>
                  <div className="account-footer">
                    <p>
                      Don't have an account yet?{" "}
                      <Link to="/register">Register</Link>
                    </p>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default Login;

// vuejs-files/template-rtl/blue/src/components/page/Login.vue
<template>
    <div class="account-page" style="height: 100vh;">
   <!-- Main Wrapper -->
   <div class="main-wrapper">
    <div class="account-content">
        
        <div class="container">
        
            <!-- Account Logo -->
            <div class="account-logo">
                <router-link to="/index"><img src="../../assets/img/logo.png" alt="Dreamguy's Technologies"></router-link>
            </div>
            <!-- /Account Logo -->
            
            <div class="account-box">
                <div class="account-wrapper">
                    <h3 class="account-title">Login</h3>
                    <p class="account-subtitle">Access to our dashboard</p>
                    
                    <!-- Account Form -->
                    <form action="index">
                        <div class="form-group">
                            <label>Email Address</label>
                            <input class="form-control" type="text">
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col">
                                    <label>Password</label>
                                </div>
                                <div class="col-auto"> 
                                    <router-link class="text-muted" to="/forgot-password">
                                        Forgot password?
                                    </router-link>
                                </div>
                            </div>
                            <input class="form-control" type="password">
                        </div>
                        <div class="form-group text-center">
                            <button class="btn btn-primary account-btn" type="submit">Login</button>
                        </div>
                        <div class="account-footer">
                            <p>Don't have an account yet? <router-link to="/register">Register</router-link></p>
                        </div>
                    </form>
                    <!-- /Account Form -->
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Main Wrapper -->
</div>
<!-- /Main Wrapper -->
</template>
